.TH PSST 1 "November 28, 2017"
.nr SM ((\n[.l] - \n[.i]) / 1n - 41)
.SH NAME
psst \- Power Stress and Shaping Tool
.SH SYNOPSIS
.\" The general command line
.B psst [options <value>]
.SH DESCRIPTION
The Power Stress and Shaping Tool (\fBPSST\fR) is a controlled power 'virus'
for Intel SoC components such as CPU and GPU.
.br
The objective is to expend virus power at run-time, varying levels for
analysis. For example, linear-ramp as a stress function on CPU can be
used to study OS governors. Likewise, a single-step function can be used
to study and determine thermal response of PID controller coefficients.
PSST enables very fine control of stress function without its own process
overhead; unlike other viruses, PSST uses its own execution flows in a
duty-cycled manner instead of "dummy work" loop. One useful artifact,
therefore, is logging of  various power and thermal system parameters at
a small fixed overhead independent of poll-period.

.SH OPTIONS
.TP
.B \-C \-\-cpumask CPUMASK
CPUMASK is hexadecimal bit mask of cpu selected. (e.g., a1 selects
cpu 0, 5, 7. default: every online cpu, maximum 1024)
.TP
.B \-p \-\-poll\-period pollperiod
pollperiod specifies period for logging in milliseconds (default 500 ms)
.TP
.B \-d \-\-duration m
specifies duration m in milliseconds to run psst (default is 3600000; 1 hour)
.TP
.B \-l \-\-log\-file path
specifies the full path to the logfile (default is /var/log/pbot.csv)
.TP
.B \-v \-\-verbose
enables verbose mode (default is disabled)
.TP
.B \-V \-\-Version
prints version
.TP
.B \-T \-\-track\-max\-cpu
Track the cpu# with maxed freq during poll period
.TP
.B \-h \-\-help
prints help
.TP
.B \-s \-\-shape\-func shape-func,arg
Specifies power shape function and argument:
.TS
expand;
lB lBw(\n[SM]n)
l l.
Shape Function	Argument
single-step,v	T{
where v is load step height [C0%]. (default shape: single-step,0.1)
T}
sinosoid,w,a	T{
where w is wavelength [seconds] and a is the amplitude (max load %)
T}
stair-case,v,u	T{
where v is load step height [C0%], u is step length (sec)
T}
single-pulse,v,u	T{
where v is load step height [C0%], u is step length (sec)
T}
linear-ramp,m	T{
where m is the slope (load/sec)
T}
saw-tooth,m,a	T{
slope m (load/sec) reversed after max a% or min(0.1)%
T}
.TE
.SH EXAMPLES
.IP 1. 4
Use psst just for logging various power/thermal parameters:
.RS 8
sudo psst	 # same as $./psst -s single-step,0.1 -p 500 -v
.RE
.IP 2. 4
Linear ramp CPU power with slope 3% usage-per-sec applied for cpu 1 and 3,
polling and reporting every 700mS, output on termial, running for 33 seconds:
.RS 8
sudo psst -s linear-ramp,3 -C a -p 700 -d 33000 -v
.RE
.SH AUTHOR
Started by Noor Mubeen
.SH COPYRIGHT
Copyright \(co 2017, Intel Corporation
License GPLv2: GNU GPL version 2
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Or, say, there is NO warranty; not even for MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.
